const $ = selector => document.querySelector(selector);
const app = { state: { sessions: [], surfaces: [], queue: [], channels: [], relays: [] }, selected: null, history: null };
const labels = { claude: 'Claude Code', codex: 'Codex', notion: 'Notion' };
globalThis.escape = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[char]));
function markdown(value) {
  let text = escape(value);
  text = text.replace(/```([^`]*)```/gs, '<pre><code>$1</code></pre>');
  text = text.replace(/^### (.+)$/gm, '<h4>$1</h4>').replace(/^## (.+)$/gm, '<h3>$1</h3>').replace(/^# (.+)$/gm, '<h2>$1</h2>');
  text = text.replace(/^[-*] (.+)$/gm, '<li>$1</li>').replace(/(<li>.*<\/li>)(?:\n<li>.*<\/li>)*/gs, match => `<ul>${match}</ul>`);
  text = text.replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g, '<a href="$2" target="_blank" rel="noreferrer">$1</a>');
  text = text.replace(/`([^`]+)`/g, '<code>$1</code>').replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>').replace(/\n/g, '<br>');
  return text;
}
const displayName = session => session?.alias ? `@${session.alias}` : (session?.name || session?.id || 'Untitled conversation');
const timeAgo = value => { const then = new Date(value).getTime(); if (!then) return 'recently'; const minutes = Math.max(0, Math.round((Date.now() - then) / 60000)); return minutes < 2 ? 'just now' : minutes < 60 ? `${minutes}m ago` : minutes < 1440 ? `${Math.round(minutes / 60)}h ago` : `${Math.round(minutes / 1440)}d ago`; };
function friendlyError(error) { return /failed to fetch|networkerror/i.test(String(error)) ? 'Agenthail cannot reach its local daemon. Start it with agenthail daemon start, then refresh this page.' : String(error); }
function toast(message) { const node = $('#toast'); node.textContent = message; node.hidden = false; clearTimeout(toast.timer); toast.timer = setTimeout(() => { node.hidden = true; }, 5000); }
function showView(name) { const allowed = ['overview', 'conversations', 'operations']; const view = allowed.includes(name) ? name : 'overview'; document.querySelectorAll('[data-view-panel]').forEach(panel => panel.classList.toggle('hidden', panel.dataset.viewPanel !== view)); document.querySelectorAll('[data-view]').forEach(link => link.classList.toggle('active', link.dataset.view === view)); if (location.hash !== `#${view}`) history.replaceState(null, '', `#${view}`); }
function statusPill(status) { return `<span class="status-pill ${escape(status)}">${escape(status)}</span>`; }
function surfaceIcon(name) { return name === 'claude' ? '✦' : name === 'codex' ? '◈' : 'N'; }
function renderOverview() {
  const { surfaces, sessions, queue } = app.state;
  const connected = surfaces.filter(surface => surface.connected);
  const busy = sessions.filter(session => session.status === 'busy');
  $('#daemon-status').textContent = app.state.daemon?.running ? 'Running locally' : 'Not running';
  $('#daemon-detail').textContent = app.state.daemon?.stale ? `Showing cached data. ${app.state.daemon.refreshError || 'Surface refresh is temporarily unavailable'}` : (app.state.daemon?.pid ? `Daemon process ${app.state.daemon.pid}` : 'Start the daemon to deliver work');
  $('#connected-count').textContent = `${connected.length} ${connected.length === 1 ? 'surface' : 'surfaces'} ready`;
  $('#active-count').textContent = `${busy.length} ${busy.length === 1 ? 'conversation' : 'conversations'} active`;
  $('#queue-summary').textContent = queue.length ? `${queue.length} ${queue.length === 1 ? 'message' : 'messages'} waiting safely` : 'Nothing waiting';
  $('#surface-cards').innerHTML = surfaces.map(surface => {
    const owned = sessions.filter(session => session.surface === surface.name);
    const active = owned.filter(session => session.status === 'busy').length;
    const queued = owned.reduce((total, session) => total + session.queueCount, 0);
    const percent = owned.length ? Math.round((active / owned.length) * 100) : 0;
    const name = labels[surface.name] || surface.name;
    return `<button class="surface-card" type="button" data-surface="${escape(surface.name)}"><div class="surface-identity"><span class="surface-logo ${escape(surface.name)}">${surfaceIcon(surface.name)}</span><div><div class="surface-name">${escape(name)}</div><div class="surface-plan">${surface.connected ? 'Connected to your local account' : (surface.error ? escape(surface.error) : 'Not connected')}</div></div></div><div><div class="surface-stats"><div><span class="stat-label">Conversations</span><span class="stat-value">${owned.length}</span></div><div><span class="stat-label">Working</span><span class="stat-value">${active}</span></div><div><span class="stat-label">Queued</span><span class="stat-value">${queued}</span></div></div><div class="bar ${active ? 'busy' : ''}"><span style="width:${percent}%"></span></div></div><div class="surface-status ${surface.connected ? '' : 'offline'}">${surface.connected ? '● READY' : '● NEEDS SETUP'}</div></button>`;
  }).join('') || '<div class="empty-card">No surfaces are configured yet. Connect Claude, Codex, or Notion and refresh.</div>';
  const recent = [...sessions].sort((a, b) => new Date(b.lastActive || 0) - new Date(a.lastActive || 0)).slice(0, 6);
  $('#recent-activity').innerHTML = recent.map(session => `<button class="activity-item" type="button" data-session="${escape(session.id)}"><div class="activity-main"><div class="activity-name"><i class="dot ${escape(session.status)}"></i>${escape(displayName(session))}</div><div class="activity-detail">${escape(labels[session.surface] || session.surface)} · ${timeAgo(session.lastActive)}</div></div>${statusPill(session.status)}</button>`).join('') || '<div class="empty-card">No conversations have appeared yet.</div>';
  $('#queue-preview').innerHTML = queue.slice(0, 4).map(item => `<div class="queue-item"><div class="activity-main"><div class="activity-name">${escape(item.target)}</div><div class="activity-detail">${escape(item.message)}</div></div>${statusPill(item.status)}</div>`).join('') || '<p class="empty-inline">No messages are waiting.</p>';
}
function renderSessions() {
  const query = $('#session-search').value.trim().toLowerCase();
  const sessions = app.state.sessions.filter(session => !query || `${displayName(session)} ${session.surface} ${session.name}`.toLowerCase().includes(query));
  $('#conversation-count').textContent = `${app.state.totalSessions || 0} discovered`;
  $('#session-list').innerHTML = sessions.map(session => `<button class="session ${app.selected?.id === session.id ? 'selected' : ''}" type="button" data-session="${escape(session.id)}"><div class="session-name"><i class="dot ${escape(session.status)}"></i>${escape(displayName(session))}</div><div class="session-detail">${escape(labels[session.surface] || session.surface)} · ${escape(session.status)}${session.queueCount ? ` · ${session.queueCount} queued` : ''}</div></button>`).join('') || '<div class="empty-card">No matching conversations.</div>';
}
function renderOperations() {
  const { queue, channels, relays } = app.state;
  $('#queue-list').innerHTML = queue.map(item => `<article class="operation-item"><div class="operation-main"><div class="operation-title">${escape(item.target)}</div><div class="operation-detail">${escape(item.message)}${item.lastError ? `<br><span style="color:var(--color-danger)">${escape(item.lastError)}</span>` : ''}</div></div><div>${statusPill(item.status)}${item.status === 'dead' ? `<button class="button quiet" data-retry="${item.id}" type="button">Retry</button>` : ''}</div></article>`).join('') || '<div class="empty-card">Delivery queue is clear.</div>';
  $('#channel-list').innerHTML = channels.map(channel => `<article class="operation-item"><div class="operation-main"><div class="operation-title">#${escape(channel.name)}</div><div class="operation-detail">${escape(channel.members.join(' · ') || 'No members yet')}</div></div><button class="button quiet" data-network-action="channel-delete" data-channel="${escape(channel.name)}" type="button">Delete</button></article>`).join('') || '<div class="empty-card">No shared channels yet.</div>';
  $('#relay-list').innerHTML = relays.map(relay => `<article class="operation-item"><div class="operation-main"><div class="operation-title">${escape(relay.from)} <span style="color:var(--color-accent)">→</span> ${escape(relay.to)}</div><div class="operation-detail">Matches /${escape(relay.pattern)}/</div></div><button class="button quiet" data-network-action="relay-remove" data-relay-id="${relay.id}" type="button">Remove</button></article>`).join('') || '<div class="empty-card">No automatic handoffs yet.</div>';
}
function renderAll() { try { renderOverview(); } catch (error) { console.error('dashboard overview render failed', error); $('#surface-cards').innerHTML = `<div class="empty-card">Could not render connected surfaces: ${escape(error.message || error)}</div>`; } renderSessions(); renderOperations(); $('#sync').textContent = `Synced ${new Date(app.state.updatedAt || Date.now()).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}`; }
async function load(fresh = false) { if (app.loading) return; app.loading = true; const slowTimer = setTimeout(() => { if (app.loading && !app.hasState) { $('#sync').textContent = 'Still connecting'; $('#daemon-detail').textContent = 'Surface discovery is taking a little longer'; $('#surface-cards').innerHTML = '<div class="empty-card">Connecting to Claude, Codex, and Notion…</div>'; } }, 2000); try { const response = await fetch(`/api/state${fresh ? '?fresh=1' : ''}`); if (!response.ok) throw Error(await response.text()); app.state = await response.json(); app.hasState = true; if (app.selected) { const replacement = app.state.sessions.find(session => session.id === app.selected.id); if (replacement) app.selected = replacement; } renderAll(); } catch (error) { const message = friendlyError(error); $('#daemon-status').textContent = 'Daemon unavailable'; $('#daemon-detail').textContent = 'Run agenthail daemon start, then refresh'; $('#surface-cards').innerHTML = `<div class="empty-card">${escape(message)}</div>`; $('#recent-activity').innerHTML = ''; $('#queue-preview').innerHTML = ''; toast(message); } finally { clearTimeout(slowTimer); app.loading = false; } }
async function selectSession(id) { const session = app.state.sessions.find(item => item.id === id); if (!session) return; app.selected = session; app.history = null; renderSessions(); showView('conversations'); $('#chat-surface').textContent = labels[session.surface] || session.surface; $('#chat-title').textContent = displayName(session); $('#chat-subtitle').textContent = `${session.status} · ${session.queueCount || 0} queued · last active ${timeAgo(session.lastActive)}`; $('#message').disabled = false; $('#send').disabled = false; $('#message').placeholder = `Message ${displayName(session)}`; $('#chat-body').innerHTML = '<div class="empty-state">Loading real conversation history…</div>'; $('#chat-actions').innerHTML = '';
  try { const response = await fetch(`/api/session?id=${encodeURIComponent(id)}`); if (!response.ok) throw Error(await response.text()); app.history = await response.json(); renderChat(); } catch (error) { $('#chat-body').innerHTML = `<div class="empty-state"><h2>Could not load this conversation</h2><p>${escape(error.message)}</p></div>`; } }
function renderChat() { const { exchanges = [], goal, model, capabilities = {} } = app.history || {}; const session = app.selected; const controls = []; if (session.status === 'busy' && capabilities.steer) controls.push('<button class="button" data-action="steer" type="button">Steer</button>'); if (session.status === 'busy' && capabilities.interrupt) controls.push('<button class="button" data-action="interrupt" type="button">Stop</button>'); if (capabilities.compact) controls.push('<button class="button" data-action="compact" type="button">Compact</button>'); $('#chat-actions').innerHTML = controls.join('');
  const toolRows = []; if (capabilities.goal) toolRows.push(`<form class="session-tools" data-tool="goal"><input name="goal" value="${escape(goal?.objective || '')}" placeholder="Set a focused goal"><button class="button" type="submit">Save goal</button>${goal?.objective ? '<button class="button quiet" data-action="goal-clear" type="button">Clear</button>' : ''}</form>`); if (capabilities.model) toolRows.push(`<form class="session-tools" data-tool="model"><input name="model" value="${escape(model || '')}" placeholder="Model name"><button class="button" type="submit">Switch model</button></form>`);
  const messages = exchanges.flatMap(exchange => [`<article class="message user"><div class="message-label">You</div>${markdown(exchange.user)}</article>`, exchange.assistant ? `<article class="message agent"><div class="message-label">${escape(labels[session.surface] || session.surface)}</div>${markdown(exchange.assistant)}</article>` : '']).join('');
  $('#chat-body').innerHTML = `${toolRows.join('')}${messages || '<div class="empty-state"><span>✦</span><h2>No saved exchanges yet</h2><p>Send a message to start this conversation from Agenthail.</p></div>'}`; $('#chat-body').scrollTop = $('#chat-body').scrollHeight;
}
async function action(action, extra = {}) { const networkAction = action.startsWith('channel-') || action.startsWith('relay-') || action === 'queue-retry'; if (!app.selected && !networkAction) throw Error('Choose a conversation first'); const response = await fetch('/api/action', { method:'POST', headers:{ 'content-type':'application/json' }, body:JSON.stringify({ action, sessionId: app.selected?.id, ...extra }) }); if (!response.ok) throw Error(await response.text()); return response.json(); }
async function send() { const message = $('#message').value.trim(); if (!message) return; $('#send').disabled = true; try { const result = await action('send', { message }); $('#message').value = ''; const queued = result.result?.disposition === 'queued'; toast(queued ? 'This agent is busy, so your message is safely queued.' : 'Message sent.'); await load(); await selectSession(app.selected.id); } catch (error) { toast(error.message); } finally { $('#send').disabled = false; } }
document.addEventListener('click', async event => { const sessionButton = event.target.closest('[data-session]'); if (sessionButton) return selectSession(sessionButton.dataset.session); const surfaceButton = event.target.closest('[data-surface]'); if (surfaceButton) { showView('conversations'); $('#session-search').value = surfaceButton.dataset.surface; renderSessions(); return; } if (event.target.closest('[data-open-conversations]')) return showView('conversations'); if (event.target.closest('[data-open-operations]')) return showView('operations'); const retry = event.target.closest('[data-retry]'); if (retry) { retry.disabled = true; try { await action('queue-retry', { queueId: Number(retry.dataset.retry) }); toast('Queued message scheduled for retry.'); await load(); } catch (error) { toast(error.message); } return; } const control = event.target.closest('[data-action]'); if (!control) return; control.disabled = true; try { await action(control.dataset.action, { message: $('#message').value.trim() }); toast(`${control.textContent} requested.`); await load(); await selectSession(app.selected.id); } catch (error) { toast(error.message); } finally { control.disabled = false; } });
$('#composer').addEventListener('submit', event => { event.preventDefault(); send(); });
document.addEventListener('submit', async event => { const form = event.target.closest('[data-tool]'); if (!form) return; event.preventDefault(); const input = form.querySelector('input'); const actionName = form.dataset.tool === 'goal' ? 'goal-set' : 'model'; const payload = form.dataset.tool === 'goal' ? { message: input.value.trim() } : { model: input.value.trim() }; try { await action(actionName, payload); toast(form.dataset.tool === 'goal' ? 'Goal saved.' : 'Model switch requested.'); await selectSession(app.selected.id); } catch (error) { toast(error.message); } });
document.addEventListener('submit', async event => { const form = event.target.closest('[data-network-form]'); if (!form) return; event.preventDefault(); const actionName = form.dataset.networkForm; const values = Object.fromEntries(new FormData(form).entries()); try { await action(actionName, values); toast(actionName === 'relay-add' ? 'Relay added.' : 'Network saved.'); form.reset(); await load(); } catch (error) { toast(error.message); } });
document.addEventListener('click', async event => { const button = event.target.closest('[data-network-action]'); if (!button) return; button.disabled = true; try { await action(button.dataset.networkAction, { channel: button.dataset.channel, relayId: Number(button.dataset.relayId || 0) }); toast('Network updated.'); await load(); } catch (error) { toast(friendlyError(error)); } });
$('#session-search').addEventListener('input', renderSessions); $('#refresh').addEventListener('click', () => load(true)); window.addEventListener('hashchange', () => showView(location.hash.slice(1))); document.addEventListener('visibilitychange', () => { if (document.visibilityState === 'visible') load(); }); showView(location.hash.slice(1) || 'overview'); load(); setInterval(() => { if (document.visibilityState === 'visible') load(); }, 10000);
